import { Metadata } from 'next/types'
import React from 'react'

export const metadata: Metadata = {
    title: 'Dashboard',
    description: 'Generated by create next app'    
}
const page = () => {
  return (
    <div>Dashboard layout</div>
  )
}

export default page